// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: proto/tradeapi/v1/common.proto

package tradeapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Market.
// Рынок.
type Market int32

const (
	// Value is not specified. Do not use.
	// Значение не указано. Не использовать.
	Market_MARKET_UNSPECIFIED Market = 0
	// Moscow Exchange Stock market.
	// Фондовый рынок Московской Биржи.
	Market_MARKET_STOCK Market = 1
	// Moscow Exchange Derivative market.
	// Срочный рынок Московской Биржи.
	Market_MARKET_FORTS Market = 4
	// Saint-Petersburg Exchange.
	// Санкт-Петербургская биржа.
	Market_MARKET_SPBEX Market = 7
	// US Stock market.
	// Фондовый рынок США.
	Market_MARKET_MMA Market = 14
	// Moscow Exchange Currency market.
	// Валютный рынок Московской Биржи.
	Market_MARKET_ETS Market = 15
	// Moscow Exchange Bond market.
	// Долговой рынок Московской Биржи.
	Market_MARKET_BONDS Market = 20
	// Moscow Exchange option market.
	// Рынок опционов Московской Биржи.
	Market_MARKET_OPTIONS Market = 21
)

// Enum value maps for Market.
var (
	Market_name = map[int32]string{
		0:  "MARKET_UNSPECIFIED",
		1:  "MARKET_STOCK",
		4:  "MARKET_FORTS",
		7:  "MARKET_SPBEX",
		14: "MARKET_MMA",
		15: "MARKET_ETS",
		20: "MARKET_BONDS",
		21: "MARKET_OPTIONS",
	}
	Market_value = map[string]int32{
		"MARKET_UNSPECIFIED": 0,
		"MARKET_STOCK":       1,
		"MARKET_FORTS":       4,
		"MARKET_SPBEX":       7,
		"MARKET_MMA":         14,
		"MARKET_ETS":         15,
		"MARKET_BONDS":       20,
		"MARKET_OPTIONS":     21,
	}
)

func (x Market) Enum() *Market {
	p := new(Market)
	*p = x
	return p
}

func (x Market) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Market) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tradeapi_v1_common_proto_enumTypes[0].Descriptor()
}

func (Market) Type() protoreflect.EnumType {
	return &file_proto_tradeapi_v1_common_proto_enumTypes[0]
}

func (x Market) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Market.Descriptor instead.
func (Market) EnumDescriptor() ([]byte, []int) {
	return file_proto_tradeapi_v1_common_proto_rawDescGZIP(), []int{0}
}

// Transaction direction.
// Направление сделки.
type BuySell int32

const (
	// Value is not specified. Do not use.
	// Значение не указано. Не использовать.
	BuySell_BUY_SELL_UNSPECIFIED BuySell = 0
	// Sell.
	// Продажа.
	BuySell_BUY_SELL_SELL BuySell = 1
	// Buy.
	// Покупка.
	BuySell_BUY_SELL_BUY BuySell = 2
)

// Enum value maps for BuySell.
var (
	BuySell_name = map[int32]string{
		0: "BUY_SELL_UNSPECIFIED",
		1: "BUY_SELL_SELL",
		2: "BUY_SELL_BUY",
	}
	BuySell_value = map[string]int32{
		"BUY_SELL_UNSPECIFIED": 0,
		"BUY_SELL_SELL":        1,
		"BUY_SELL_BUY":         2,
	}
)

func (x BuySell) Enum() *BuySell {
	p := new(BuySell)
	*p = x
	return p
}

func (x BuySell) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuySell) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tradeapi_v1_common_proto_enumTypes[1].Descriptor()
}

func (BuySell) Type() protoreflect.EnumType {
	return &file_proto_tradeapi_v1_common_proto_enumTypes[1]
}

func (x BuySell) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuySell.Descriptor instead.
func (BuySell) EnumDescriptor() ([]byte, []int) {
	return file_proto_tradeapi_v1_common_proto_rawDescGZIP(), []int{1}
}

// Time validation for order.
// Установка временных рамок действия заявки.
type OrderValidBeforeType int32

const (
	// Value is not specified. Do not use.
	// Значение не указано. Не использовать.
	OrderValidBeforeType_ORDER_VALID_BEFORE_TYPE_UNSPECIFIED OrderValidBeforeType = 0
	// Order is valid till the end of the current session.
	// Заявка действует до конца сессии.
	OrderValidBeforeType_ORDER_VALID_BEFORE_TYPE_TILL_END_SESSION OrderValidBeforeType = 1
	// Order is valid till cancellation.
	// Заявка действует, пока не будет отменена.
	OrderValidBeforeType_ORDER_VALID_BEFORE_TYPE_TILL_CANCELLED OrderValidBeforeType = 2
	// Order is valid till specified moment. OrderValidBefore.time parameter must be set.
	// Заявка действует до указанного времени. Параметр OrderValidBefore.time должно быть установлен.
	OrderValidBeforeType_ORDER_VALID_BEFORE_TYPE_EXACT_TIME OrderValidBeforeType = 3
)

// Enum value maps for OrderValidBeforeType.
var (
	OrderValidBeforeType_name = map[int32]string{
		0: "ORDER_VALID_BEFORE_TYPE_UNSPECIFIED",
		1: "ORDER_VALID_BEFORE_TYPE_TILL_END_SESSION",
		2: "ORDER_VALID_BEFORE_TYPE_TILL_CANCELLED",
		3: "ORDER_VALID_BEFORE_TYPE_EXACT_TIME",
	}
	OrderValidBeforeType_value = map[string]int32{
		"ORDER_VALID_BEFORE_TYPE_UNSPECIFIED":      0,
		"ORDER_VALID_BEFORE_TYPE_TILL_END_SESSION": 1,
		"ORDER_VALID_BEFORE_TYPE_TILL_CANCELLED":   2,
		"ORDER_VALID_BEFORE_TYPE_EXACT_TIME":       3,
	}
)

func (x OrderValidBeforeType) Enum() *OrderValidBeforeType {
	p := new(OrderValidBeforeType)
	*p = x
	return p
}

func (x OrderValidBeforeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderValidBeforeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tradeapi_v1_common_proto_enumTypes[2].Descriptor()
}

func (OrderValidBeforeType) Type() protoreflect.EnumType {
	return &file_proto_tradeapi_v1_common_proto_enumTypes[2]
}

func (x OrderValidBeforeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderValidBeforeType.Descriptor instead.
func (OrderValidBeforeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_tradeapi_v1_common_proto_rawDescGZIP(), []int{2}
}

// Request execution result.
// Результат выполнения запроса.
type ResponseEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Request ID.
	// Идентификатор запроса.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Request execution result.
	// Результат выполнения запроса.
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Errors in request execution.
	// Ошибки выполнения запроса.
	Errors []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *ResponseEvent) Reset() {
	*x = ResponseEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tradeapi_v1_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEvent) ProtoMessage() {}

func (x *ResponseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tradeapi_v1_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEvent.ProtoReflect.Descriptor instead.
func (*ResponseEvent) Descriptor() ([]byte, []int) {
	return file_proto_tradeapi_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResponseEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseEvent) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Error data.
// Данные об ошибке.
type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Error code.
	// Код ошибки.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Error message.
	// Сообщение об ошибке.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tradeapi_v1_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tradeapi_v1_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_tradeapi_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Order time condition.
// Условие по времени действия заявки.
type OrderValidBefore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Condition type.
	// Тип условия.
	Type OrderValidBeforeType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.tradeapi.v1.OrderValidBeforeType" json:"type,omitempty"`
	// Order lifetime.
	// Время действия заявки.
	Time *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *OrderValidBefore) Reset() {
	*x = OrderValidBefore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tradeapi_v1_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderValidBefore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderValidBefore) ProtoMessage() {}

func (x *OrderValidBefore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tradeapi_v1_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderValidBefore.ProtoReflect.Descriptor instead.
func (*OrderValidBefore) Descriptor() ([]byte, []int) {
	return file_proto_tradeapi_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *OrderValidBefore) GetType() OrderValidBeforeType {
	if x != nil {
		return x.Type
	}
	return OrderValidBeforeType_ORDER_VALID_BEFORE_TYPE_UNSPECIFIED
}

func (x *OrderValidBefore) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

// Real number with fixed precision (including integers).
// The total value is calculated as follows: num * 10^-scale.
// https://en.wikipedia.org/wiki/Scientific_notation
// Example:
// The number "250.655" is Decimal type with num = 250655 and scale = 3, 250.655 = 250655 * 10^-3
type Decimal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Mantissa.
	// Мантисса.
	Num int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	// exponent for base 10.
	// Экспонента.
	Scale uint32 `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tradeapi_v1_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tradeapi_v1_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_proto_tradeapi_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Decimal) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Decimal) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

var File_proto_tradeapi_v1_common_proto protoreflect.FileDescriptor

var file_proto_tradeapi_v1_common_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x30,
	0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7f, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x07, 0x44, 0x65, 0x63, 0x69,
	0x6d, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x2a, 0x9c, 0x01, 0x0a, 0x06,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x4f, 0x43, 0x4b, 0x10, 0x01,
	0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x46, 0x4f, 0x52, 0x54, 0x53,
	0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x53, 0x50, 0x42,
	0x45, 0x58, 0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x4d,
	0x4d, 0x41, 0x10, 0x0e, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x45,
	0x54, 0x53, 0x10, 0x0f, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x42,
	0x4f, 0x4e, 0x44, 0x53, 0x10, 0x14, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54,
	0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x10, 0x15, 0x2a, 0x48, 0x0a, 0x07, 0x42, 0x75,
	0x79, 0x53, 0x65, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x14, 0x42, 0x55, 0x59, 0x5f, 0x53, 0x45, 0x4c,
	0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x42, 0x55, 0x59, 0x5f, 0x53, 0x45, 0x4c, 0x4c, 0x5f, 0x53, 0x45, 0x4c, 0x4c,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x55, 0x59, 0x5f, 0x53, 0x45, 0x4c, 0x4c, 0x5f, 0x42,
	0x55, 0x59, 0x10, 0x02, 0x2a, 0xc1, 0x01, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a,
	0x23, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x42, 0x45, 0x46,
	0x4f, 0x52, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x2c, 0x0a, 0x28, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x42, 0x45, 0x46, 0x4f, 0x52, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x54, 0x49, 0x4c, 0x4c, 0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49,
	0x4f, 0x4e, 0x10, 0x01, 0x12, 0x2a, 0x0a, 0x26, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x42, 0x45, 0x46, 0x4f, 0x52, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x54, 0x49, 0x4c, 0x4c, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x26, 0x0a, 0x22, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f,
	0x42, 0x45, 0x46, 0x4f, 0x52, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x58, 0x41, 0x43,
	0x54, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x03, 0x42, 0x4a, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x76, 0x73, 0x61, 0x6d, 0x73, 0x6f, 0x6e, 0x6f,
	0x76, 0x2f, 0x46, 0x69, 0x6e, 0x61, 0x6d, 0x54, 0x72, 0x61, 0x64, 0x65, 0x47, 0x6f, 0x2f, 0x76,
	0x32, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0xaa, 0x02, 0x17, 0x46, 0x69, 0x6e,
	0x61, 0x6d, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x41, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_tradeapi_v1_common_proto_rawDescOnce sync.Once
	file_proto_tradeapi_v1_common_proto_rawDescData = file_proto_tradeapi_v1_common_proto_rawDesc
)

func file_proto_tradeapi_v1_common_proto_rawDescGZIP() []byte {
	file_proto_tradeapi_v1_common_proto_rawDescOnce.Do(func() {
		file_proto_tradeapi_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tradeapi_v1_common_proto_rawDescData)
	})
	return file_proto_tradeapi_v1_common_proto_rawDescData
}

var file_proto_tradeapi_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_tradeapi_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_tradeapi_v1_common_proto_goTypes = []interface{}{
	(Market)(0),                   // 0: proto.tradeapi.v1.Market
	(BuySell)(0),                  // 1: proto.tradeapi.v1.BuySell
	(OrderValidBeforeType)(0),     // 2: proto.tradeapi.v1.OrderValidBeforeType
	(*ResponseEvent)(nil),         // 3: proto.tradeapi.v1.ResponseEvent
	(*Error)(nil),                 // 4: proto.tradeapi.v1.Error
	(*OrderValidBefore)(nil),      // 5: proto.tradeapi.v1.OrderValidBefore
	(*Decimal)(nil),               // 6: proto.tradeapi.v1.Decimal
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_tradeapi_v1_common_proto_depIdxs = []int32{
	4, // 0: proto.tradeapi.v1.ResponseEvent.errors:type_name -> proto.tradeapi.v1.Error
	2, // 1: proto.tradeapi.v1.OrderValidBefore.type:type_name -> proto.tradeapi.v1.OrderValidBeforeType
	7, // 2: proto.tradeapi.v1.OrderValidBefore.time:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_tradeapi_v1_common_proto_init() }
func file_proto_tradeapi_v1_common_proto_init() {
	if File_proto_tradeapi_v1_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_tradeapi_v1_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tradeapi_v1_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tradeapi_v1_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderValidBefore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tradeapi_v1_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Decimal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tradeapi_v1_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_tradeapi_v1_common_proto_goTypes,
		DependencyIndexes: file_proto_tradeapi_v1_common_proto_depIdxs,
		EnumInfos:         file_proto_tradeapi_v1_common_proto_enumTypes,
		MessageInfos:      file_proto_tradeapi_v1_common_proto_msgTypes,
	}.Build()
	File_proto_tradeapi_v1_common_proto = out.File
	file_proto_tradeapi_v1_common_proto_rawDesc = nil
	file_proto_tradeapi_v1_common_proto_goTypes = nil
	file_proto_tradeapi_v1_common_proto_depIdxs = nil
}
