// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: grpc/tradeapi/v1/securities.proto

package tradeapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Securities list request.
// Запрос списка инструментов.
type GetSecuritiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSecuritiesRequest) Reset() {
	*x = GetSecuritiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_securities_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSecuritiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecuritiesRequest) ProtoMessage() {}

func (x *GetSecuritiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_securities_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecuritiesRequest.ProtoReflect.Descriptor instead.
func (*GetSecuritiesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_securities_proto_rawDescGZIP(), []int{0}
}

// Result of get security lists request.
// Результат выполнения запроса списка инструментов.
type GetSecuritiesResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Securities list.
	// Список инструментов.
	Securities []*Security `protobuf:"bytes,1,rep,name=securities,proto3" json:"securities,omitempty"`
}

func (x *GetSecuritiesResult) Reset() {
	*x = GetSecuritiesResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_tradeapi_v1_securities_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSecuritiesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecuritiesResult) ProtoMessage() {}

func (x *GetSecuritiesResult) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_securities_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecuritiesResult.ProtoReflect.Descriptor instead.
func (*GetSecuritiesResult) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_securities_proto_rawDescGZIP(), []int{1}
}

func (x *GetSecuritiesResult) GetSecurities() []*Security {
	if x != nil {
		return x.Securities
	}
	return nil
}

var File_grpc_tradeapi_v1_securities_proto protoreflect.FileDescriptor

var file_grpc_tradeapi_v1_securities_proto_rawDesc = []byte{
	0x0a, 0x21, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61,
	0x64, 0x65, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x63, 0x75, 0x72, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x52, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3b, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x32, 0x6c, 0x0a, 0x0a, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x12, 0x5e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x12, 0x26, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x42, 0x49, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x76, 0x73, 0x61, 0x6d, 0x73, 0x6f, 0x6e, 0x6f, 0x76, 0x2f, 0x46, 0x69, 0x6e, 0x61, 0x6d,
	0x54, 0x72, 0x61, 0x64, 0x65, 0x47, 0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x61, 0x70, 0x69, 0xaa, 0x02, 0x16, 0x46, 0x69, 0x6e, 0x61, 0x6d, 0x2e, 0x54, 0x72, 0x61, 0x64,
	0x65, 0x41, 0x70, 0x69, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_tradeapi_v1_securities_proto_rawDescOnce sync.Once
	file_grpc_tradeapi_v1_securities_proto_rawDescData = file_grpc_tradeapi_v1_securities_proto_rawDesc
)

func file_grpc_tradeapi_v1_securities_proto_rawDescGZIP() []byte {
	file_grpc_tradeapi_v1_securities_proto_rawDescOnce.Do(func() {
		file_grpc_tradeapi_v1_securities_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_tradeapi_v1_securities_proto_rawDescData)
	})
	return file_grpc_tradeapi_v1_securities_proto_rawDescData
}

var file_grpc_tradeapi_v1_securities_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_tradeapi_v1_securities_proto_goTypes = []interface{}{
	(*GetSecuritiesRequest)(nil), // 0: grpc.tradeapi.v1.GetSecuritiesRequest
	(*GetSecuritiesResult)(nil),  // 1: grpc.tradeapi.v1.GetSecuritiesResult
	(*Security)(nil),             // 2: proto.tradeapi.v1.Security
}
var file_grpc_tradeapi_v1_securities_proto_depIdxs = []int32{
	2, // 0: grpc.tradeapi.v1.GetSecuritiesResult.securities:type_name -> proto.tradeapi.v1.Security
	0, // 1: grpc.tradeapi.v1.Securities.GetSecurities:input_type -> grpc.tradeapi.v1.GetSecuritiesRequest
	1, // 2: grpc.tradeapi.v1.Securities.GetSecurities:output_type -> grpc.tradeapi.v1.GetSecuritiesResult
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_tradeapi_v1_securities_proto_init() }
func file_grpc_tradeapi_v1_securities_proto_init() {
	if File_grpc_tradeapi_v1_securities_proto != nil {
		return
	}
	file_proto_tradeapi_v1_security_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_grpc_tradeapi_v1_securities_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSecuritiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_tradeapi_v1_securities_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSecuritiesResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_tradeapi_v1_securities_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_tradeapi_v1_securities_proto_goTypes,
		DependencyIndexes: file_grpc_tradeapi_v1_securities_proto_depIdxs,
		MessageInfos:      file_grpc_tradeapi_v1_securities_proto_msgTypes,
	}.Build()
	File_grpc_tradeapi_v1_securities_proto = out.File
	file_grpc_tradeapi_v1_securities_proto_rawDesc = nil
	file_grpc_tradeapi_v1_securities_proto_goTypes = nil
	file_grpc_tradeapi_v1_securities_proto_depIdxs = nil
}
